### ISSUE TITLE
Error testing vue component that uses ckeditor5-vue

### ISSUE THREAD

**Issue by upadhb** [ckeditor/ckeditor5-vue#128]
Hi all,

I have a vue project where I am using vue-test-utils and Jest for unit testing. While trying to run test on my component that has ckEditor5, I get the following error originating from **\node_modules\@ckeditor\ckeditor5-editor-classic\src\classiceditor.js:10** 
![image](https://user-images.githubusercontent.com/17695919/77038934-fe656180-69dc-11ea-8395-e84d4f903116.png)

I followed the documentation for configuring vue.config.js. Is there some sort of configuration required for jest.config.js as well?

Please help

This is how I am using the editor:
**In main.js**
```
import CKEditor from '@ckeditor/ckeditor5-vue';
Vue.use(CKEditor);
```
I created a mixin (like below) that I import in my component:

```
import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
import EssentialsPlugin from '@ckeditor/ckeditor5-essentials/src/essentials';
import BoldPlugin from '@ckeditor/ckeditor5-basic-styles/src/bold';
import ItalicPlugin from '@ckeditor/ckeditor5-basic-styles/src/italic';
import LinkPlugin from '@ckeditor/ckeditor5-link/src/link';
import Underline from '@ckeditor/ckeditor5-basic-styles/src/underline';
import ParagraphPlugin from '@ckeditor/ckeditor5-paragraph/src/paragraph';
import Heading from '@ckeditor/ckeditor5-heading/src/heading';
import Alignment from '@ckeditor/ckeditor5-alignment/src/alignment';
import List from '@ckeditor/ckeditor5-list/src/list';

export default {
    data() {
        return {
            editor: ClassicEditor,
            editorConfig: {
                plugins: [
                    EssentialsPlugin,
                    BoldPlugin,
                    ItalicPlugin,
                    Underline,
                    LinkPlugin,
                    ParagraphPlugin,
                    Heading,
                    Alignment,
                    List,
                ],

                toolbar: {
                    items: [
                        'heading',
                        '|',
                        'bold',
                        'italic',
                        'underline',
                        '|',
                        'numberedList',
                        '|',
                        'bulletedList',
                        '|',
                        'link',
                        '|',
                        'alignment',
                        '|',
                        'undo',
                        'redo',
                    ],
                },
            },
        };
    },
};
```

**Comment by FilipTokarski** [comment]
Hi! Thanks for the report, unfortunately I can confirm this. When running tests using _vue-test-utils_ & Jest I get the same error:
```js
import Editor from '@ckeditor/ckeditor5-core/src/editor/editor';
           ^^^^^^

    SyntaxError: Unexpected identifier

       7 | <script>
       8 | import CKEditor from "@ckeditor/ckeditor5-vue";
    >  9 | import ClassicEditor from '@ckeditor/ckeditor5-editor-classic/src/classiceditor';
         | ^
      10 | import EssentialsPlugin from '@ckeditor/ckeditor5-essentials/src/essentials';
      11 | import BoldPlugin from '@ckeditor/ckeditor5-basic-styles/src/bold';
      12 | import ItalicPlugin from '@ckeditor/ckeditor5-basic-styles/src/italic';

      at ScriptTransformer._transformAndBuildScript (node_modules/@jest/transform/build/ScriptTransformer.js:537:17)
      at ScriptTransformer.transform (node_modules/@jest/transform/build/ScriptTransformer.js:579:25)
      at src/components/CKEditor.vue:9:1
      at Object.<anonymous> (src/components/CKEditor.vue:57:3)

```

cc @oleq

**Comment by upadhb** [comment]
Is there a way to resolve this??

**Comment by oleq** [comment]
@upadhb Have you tried suggestions in https://github.com/ckeditor/ckeditor5-vue/issues/50?

**Comment by FilipTokarski** [comment]
I'm closing this due to lack of activity.

**Comment by rafapaulin** [comment]
Still not solved =/ same problem here

**Comment by JarvisH** [comment]
Finally got this working, although I'm not sure what did the trick.

What I did:
1) Update all CKeditor dependencies to 27.1.0
2) Add vue.config.js Webpack configuration per the [CKeditor documentation](https://ckeditor.com/docs/ckeditor5/latest/builds/guides/integration/frameworks/vuejs-v3.html#configuring-vueconfigjs)
3) Adjust `transformIgnorePatterns` in jest.config.js like this:

```js
  transformIgnorePatterns: [
    '/node_modules/(?!lodash-es)(?!@ckeditor/*)(?!ckeditor5/*)', // transform all ckeditor dependencies
    '\\.pnp\\.[^\\/]+$'
  ],
```

4) If you are mocking static files: make sure svgs from CKeditor are not being mocked/stubbed in `moduleNameWrapper`:

```js
  moduleNameMapper: {
    // Don't add 'svg' here...
    '\\.(jpg|jpeg|png|gif|eot|otf|webp|ttf|woff|woff2|mp4|webm|wav|mp3|m4a|aac|oga)$': 
      '<rootDir>/__mocks__/fileMock.ts',
    // instead only add entry for svgs which are part of your project
    // adjust to fit your svg paths
    '(assets\\/svg\\/.*\\.svg)$': '<rootDir>/__mocks__/fileMock.ts'
  },
```

**Comment by RahulRawat1994** [comment]
Still not working
