### ISSUE TITLE
ckeditor5-dev-webpack-plugin fails to build ckeditor

### ISSUE THREAD

**Issue by themnd** [ckeditor/ckeditor5-vue#136]
Hello,

my build fails with some strange errors, first it complains about wrong translations like https://github.com/ckeditor/ckeditor5-vue/issues/134, then it fails with:

```
ERROR  Failed to compile with 22 errors                                                          3:45:02 PM

 error  in ./node_modules/@ckeditor/ckeditor5-essentials/src/essentials.js

Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
this.query.translateSource is not a function
    at PoolWorker.fromErrorObj (/app/client/node_modules/thread-loader/dist/WorkerPool.js:262:12)
    at /app/client/node_modules/thread-loader/dist/WorkerPool.js:204:29
    at mapSeries (/app/client/node_modules/neo-async/async.js:3625:14)
    at PoolWorker.onWorkerMessage (/app/client/node_modules/thread-loader/dist/WorkerPool.js:170:35)
    at /app/client/node_modules/thread-loader/dist/WorkerPool.js:152:14
    at Socket.onChunk (/app/client/node_modules/thread-loader/dist/readBuffer.js:36:9)
    at Object.translateSourceLoader (/app/client/node_modules/@ckeditor/ckeditor5-dev-webpack-plugin/lib/translatesourceloader.js:20:20)
```

all the errors looks the same.

If I modify ./node_modules/@ckeditor/ckeditor5-dev-webpack-plugin/lib/translatesourceloader.js, simply doing:

```
module.exports = function translateSourceLoader( source ) {
    if (this.query.translateSource) {
        console.log("***** this.resourcePath", this.resourcePath);
        console.log("***** this.query", this.query);
        console.log("***** this.query.translateSource", this.query.translateSource);
        return this.query.translateSource( source, this.resourcePath );
    } else {
        return source;
    }
};
```

then the build runs fine (message with ***** are never shown...) and I got these warnings:

```
warning

Conflict: Multiple assets emit different content to the same filename translations/en.js

 warning

Conflict: Multiple assets emit different content to the same filename translations/it.js
```

ckeditor is used with:

```
import CKEditor from "@ckeditor/ckeditor5-vue";
import InlineEditor from "@ckeditor/ckeditor5-editor-inline/src/inlineeditor";
import EssentialsPlugin from "@ckeditor/ckeditor5-essentials/src/essentials";
import AutoformatPlugin from "@ckeditor/ckeditor5-autoformat/src/autoformat";
import BlockQuotePlugin from "@ckeditor/ckeditor5-block-quote/src/blockquote";
import BoldPlugin from "@ckeditor/ckeditor5-basic-styles/src/bold";
import CKFinder from "@ckeditor/ckeditor5-ckfinder/src/ckfinder";
import EasyImagePlugin from "@ckeditor/ckeditor5-easy-image/src/easyimage";
import FileRepository from "@ckeditor/ckeditor5-upload/src/filerepository";
import HeadingPlugin from "@ckeditor/ckeditor5-heading/src/heading";
import ImageCaptionPlugin from "@ckeditor/ckeditor5-image/src/imagecaption";
import ImagePlugin from "@ckeditor/ckeditor5-image/src/image";
import ImageStylePlugin from "@ckeditor/ckeditor5-image/src/imagestyle";
import ImageToolbarPlugin from "@ckeditor/ckeditor5-image/src/imagetoolbar";
import ImageUploadPlugin from "@ckeditor/ckeditor5-image/src/imageupload";
import ItalicPlugin from "@ckeditor/ckeditor5-basic-styles/src/italic";
import LinkPlugin from "@ckeditor/ckeditor5-link/src/link";
import ListPlugin from "@ckeditor/ckeditor5-list/src/list";
import MediaEmbed from "@ckeditor/ckeditor5-media-embed/src/mediaembed";
import ParagraphPlugin from "@ckeditor/ckeditor5-paragraph/src/paragraph";
import Table from "@ckeditor/ckeditor5-table/src/table";
import TableToolbar from "@ckeditor/ckeditor5-table/src/tabletoolbar";
import WordCount from "@ckeditor/ckeditor5-word-count/src/wordcount";
```

my package.json contains:

```
  "dependencies": {
    "@ckeditor/ckeditor5-adapter-ckfinder": "^19.0.0",
    "@ckeditor/ckeditor5-autoformat": "^19.0.0",
    "@ckeditor/ckeditor5-basic-styles": "^19.0.0",
    "@ckeditor/ckeditor5-block-quote": "^19.0.0",
    "@ckeditor/ckeditor5-ckfinder": "^19.0.1",
    "@ckeditor/ckeditor5-dev-utils": "^20.0.0",
    "@ckeditor/ckeditor5-dev-webpack-plugin": "^20.0.0",
    "@ckeditor/ckeditor5-easy-image": "^19.0.0",
    "@ckeditor/ckeditor5-editor-inline": "^19.0.0",
    "@ckeditor/ckeditor5-essentials": "^19.0.0",
    "@ckeditor/ckeditor5-heading": "^19.0.0",
    "@ckeditor/ckeditor5-image": "^19.0.0",
    "@ckeditor/ckeditor5-link": "^19.0.0",
    "@ckeditor/ckeditor5-list": "^19.0.0",
    "@ckeditor/ckeditor5-media-embed": "^19.1.0",
    "@ckeditor/ckeditor5-paragraph": "^19.0.0",
    "@ckeditor/ckeditor5-table": "^19.1.0",
    "@ckeditor/ckeditor5-theme-lark": "^19.0.0",
    "@ckeditor/ckeditor5-upload": "^19.0.1",
    "@ckeditor/ckeditor5-vue": "^1.0.1",
    "@ckeditor/ckeditor5-word-count": "^19.0.0",
```

and in dev dependencies i have:

```
  "devDependencies": {
    "@vue/cli-plugin-babel": "^3.12.1",
    "@vue/cli-plugin-eslint": "^3.12.1",
    "@vue/cli-service": "^3.12.1",
    "@vue/eslint-config-prettier": "^4.0.1",
    "babel-eslint": "^10.1.0",
    "eslint": "^5.16.0",
    "eslint-config-airbnb-base": "^14.1.0",
    "eslint-config-prettier": "^6.11.0",
    "eslint-plugin-import": "^2.20.2",
    "eslint-plugin-prettier": "^3.1.3",
    "eslint-plugin-vue": "^5.2.3",
    "postcss-loader": "^3.0.0",
    "raw-loader": "^0.5.1",
    "vue-template-compiler": "^2.6.11"
  }
```

my script section is:

```
  "scripts": {
    "serve": "vue-cli-service serve --port 8082 --mode=development",
    "build-staging": "vue-cli-service build --mode=staging",
    "build": "vue-cli-service build --mode=production",
    "lint": "vue-cli-service lint"
  },
```

this problem happens only when running `npm run build`.
If I run `npm run serve` I can see the logs messages starting with "\*\*\*\*".

If I modify ./node_modules/@ckeditor/ckeditor5-dev-webpack-plugin/lib/translatesourceloader.js, in this way:

```
module.exports = function translateSourceLoader( source ) {
    if (this.query.translateSource) {
        console.log("***** this.resourcePath", this.resourcePath);
        console.log("***** this.query", this.query);
        console.log("***** this.query.translateSource", this.query.translateSource);
        return this.query.translateSource( source, this.resourcePath );
    } else {
        return this.query.translateSource( source, this.resourcePath );
    }
};
```

and I run `npm run build-staging` i cannot see the log messages starting with "\*\*\*\*" but the build runs fine.

**Comment by FilipTokarski** [comment]
cc @ma2ciek

**Comment by themnd** [comment]
Just verified that the problem does not happen on windows.
I was testing it on a mac.

**Comment by themnd** [comment]
on windows after having removed the node_modules and done `npm install` again, I now have the same problem.

**Comment by gomyho** [comment]
the same error！！ ,but some time occurs,when checkout diff branch it build success and errors else ,curiously is thant the package.json is same,and config is same;platform: latest macos pro

**Comment by ByteFinance** [comment]
same problem.

**Comment by GuoYingxu** [comment]
same problem

**Comment by ma2ciek** [comment]
Hi, could you reinstall everything and try again?

I'm not sure but it seems that our `CKEditorWebpackPlugin` doesn't work with  `thread-loader`. So if you don't need UI localization you can just remove this plugin from the webpack configuration.

**Comment by ma2ciek** [comment]
It seems that this loader is added sometimes by Vue when the production build pipeline is used. For me it's quite strange as the loader is quite limited - https://github.com/webpack-contrib/thread-loader/#usage.

**Comment by ma2ciek** [comment]
I'd try setting `parallel` to `false` in the `vue.config.js` and see it it works - https://cli.vuejs.org/config/#parallel.

**Comment by gpstash** [comment]
use `parallel: false` works for me

**Comment by Mgsy** [comment]
I'm closing it as the issue seems to be solved.

**Comment by yxlolxy** [comment]
> on windows after having removed the node_modules and done `npm install` again, I now have the same problem.

me too!

**Comment by dpointk** [comment]
> use `parallel: false` works for me @ma2ciek

this worked for me too. tx!

**Comment by gpp8p** [comment]
Could somebody give me an example of setting parallel: false in vue.config.js ?

**Comment by HephaestosSmith** [comment]
> Could somebody give me an example of setting parallel: false in vue.config.js ?

module.exports = {
  parallel: false,
  chainWebpack: (config) => {
     ...
     ...
  },
};
