### ISSUE TITLE
build failed with vite

### ISSUE THREAD

**Issue by minyoung90** [ckeditor/ckeditor5-vue#232]
https://github.com/ckeditor/ckeditor5/issues/9807

I followed above instructions (with custom build)
so, I can do "npm run dev" with no errors but, when I did "npm run build", I failed it.

I got this errors, I need help!
```
error during build:
Error: 'default' is not exported by ckeditor5/build/ckeditor.js, imported by src/views/CKEditorView.vue?vue&type=script&setup=true&lang.ts
    at error (file:///home/myc/dev/research/research-ckeditor-v5/node_modules/rollup/dist/es/shared/rollup.js:1858:30)
    at Module.error (file:///home/myc/dev/research/research-ckeditor-v5/node_modules/rollup/dist/es/shared/rollup.js:12429:16)
    at Module.traceVariable (file:///home/myc/dev/research/research-ckeditor-v5/node_modules/rollup/dist/es/shared/rollup.js:12788:29)
    at ModuleScope.findVariable (file:///home/myc/dev/research/research-ckeditor-v5/node_modules/rollup/dist/es/shared/rollup.js:11440:39)
    at FunctionScope.findVariable (file:///home/myc/dev/research/research-ckeditor-v5/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at ChildScope.findVariable (file:///home/myc/dev/research/research-ckeditor-v5/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at ReturnValueScope.findVariable (file:///home/myc/dev/research/research-ckeditor-v5/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at ChildScope.findVariable (file:///home/myc/dev/research/research-ckeditor-v5/node_modules/rollup/dist/es/shared/rollup.js:6372:38)
    at Identifier.bind (file:///home/myc/dev/research/research-ckeditor-v5/node_modules/rollup/dist/es/shared/rollup.js:7439:40)
    at CallExpression.bind (file:///home/myc/dev/research/research-ckeditor-v5/node_modules/rollup/dist/es/shared/rollup.js:5265:73)
```

**Comment by ralph10D** [comment]
@minyoung90  I get the same error. Did you find a way around this?

**Comment by RaidPRDev** [comment]
Also had trouble getting CK Editor running. It worked making builds for dev, but not for production.

My setup:
```
"vue": "^3.2.41"
"vite": "^3.0.2"
"vue-tsc": "^0.35.0"
"typescript": "^4.5.4"
```

**Ultimately my fix was to npm install -> rollup-plugin-commonjs
After that I was able to make production builds.**

## Instructions
I will try to be thorough as I can on exactly what I did to get it running.  
First check this, ( last bullet point === Error: 'default' is not exported by node_modules/vue-runtime-helpers/dist/normalize-component.js )
https://rollup-plugin-vue.vuejs.org/faqs.html

## Step1: Install the the following libraries:
```
npm install rollup-plugin-commonjs --save-dev
npm install @ckeditor/ckeditor5-vue --save-dev
```

## Step 2: Create Custom CK Editor Build
- You will need to go to https://ckeditor.com/ckeditor-5/online-builder/
- Make your build and download.
- In your project root folder, create a folder called "libs", the location/name does not matter.  
- In the "libs" folder, create another folder called "ckeditor5"
- Copy the contents of the generated CKEditor build zip file you downloaded.
- Then add it to the package.json; Like so: `"ckeditor5-custom-build": "file:libs/ckeditor5",`

## Step 3: In the vite.config.js
- Add import: `import commonjs from 'rollup-plugin-commonjs'`
- Then in the defineConfig return:
```
build: {
   commonjsOptions: {
       exclude: [
             'ckeditor5-custom-build', 
       ]
   }
},
optimizeDeps: {
      include: [
            'ckeditor5-custom-build',
      ],
}
```

## Step 4: Finally add the damn thing to your Vue Component
- Add the imports:
```
import CKEditor from '@ckeditor/ckeditor5-vue';
import Editor from 'ckeditor5-custom-build'
```
- In your template:
`<CKEditor.component :editor="Editor" v-model="state.formData.body"></CKEditor.component>`

Hope this helps someone.  Happy coding!

**Comment by ralph10D** [comment]
Thanks @RaidPRDev for your detailed answer!

I've followed your steps but getting a different error now when including rollup-plugin-commonjs in my vite.config.js.

```
Error: 'vue3Debounce' is not exported by node_modules/vue-debounce/dist/vue-debounce.min.js, imported by resources/js/app.js
```

**Comment by mabryl** [comment]
Hi @minyoung90 ,

Thanks for reaching out. I can see that you're using Vite as your build environment and that's something that, until very recently, we didn't support - we used webpack for all our official integrations.

Having said that, as of Decemeber 22nd, we do have an experimental plugin that allows for building CKEditor 5 from source using Vite. You can learn more about it [here](https://github.com/ckeditor/ckeditor5/issues/9807#issuecomment-1363284224).

I'll be closing this issue now and I encourage you to continue discussing the CKE5 + Vite integration in the linked thread.
